version: '3'
services:
  db:    
    image: "postgres"

  keystone:
    build:
      context: ./keystone
    depends_on:
      - db
    ports:
      - 5000:5000
    environment:
      - TESTING=true

  glance:
    build:
      context: ./glance
    depends_on:
      - db
      - keystone
    ports:
      - 5001:5000      
    environment:
      - TESTING=true
    
  placement:
    build:
      context: ./placement
    depends_on:
      - db
      - keystone
    ports:
      - 5002:5000
    environment:
      - TESTING=true
