version: '3'
services:
  db:    
    image: "postgres"

  rabbit:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=openstack
      - RABBITMQ_DEFAULT_PASS=openstack

  keystone:
    build:
      context: ./keystone
    depends_on:
      - db
    ports:
      - 5000:5000
    environment:
      - TESTING=true

  glance:
    build:
      context: ./glance
    depends_on:
      - db
      - keystone
    ports:
      - 5001:5000      
    environment:
      - TESTING=true
    
  placement:
    build:
      context: ./placement
    depends_on:
      - db
      - keystone
    ports:
      - 5002:5000
    environment:
      - TESTING=true
 
  nova-api:
    build:
      context: ./nova
    depends_on:
      - db
      - rabbit
      - keystone
    ports:
      - 5003:5000
    environment:
      - TESTING=true
     
